#!/usr/bin/env python
import os

def pretty_print(alist):
    for item in alist:
        print str(item)
    print '\nControl-C to Kill\n'
print '\n'
list_vols = os.listdir('/Volumes')
number_of_volumes = len(list_vols)
pretty_print(list_vols)
while True:
    for volume in list_vols:
        list_vols = os.listdir('/Volumes')
        if number_of_volumes != len(list_vols):
            pretty_print(list_vols)
            number_of_volumes = len(list_vols)
