#!/usr/bin/env python

from VideoFile import *
from SD import *
from importManager import *
from ttk import *
from Tkinter import *


class VRFriend(Frame):

    def __init__(self, master=None):
       Frame.__init__(self, master)
       self.pack()
       self.quit_button = self.button(LEFT, 'Quit', self.quit)
       self.location = self.entry(LEFT, 'location')
       self.camera = self.entry(LEFT, 'camera')

    def frame(self, side):
        w = Frame()
        w.pack(side=side, expand=YES, fill=BOTH)
        return w

    def button(self, side, text, command=None):
        w = Button(text=text, command=command)
        w.pack(side=side, expand=YES, fill=BOTH)
        return w

    def entry(self, side, text, command=None):
        contents = StringVar()
        contents.set(text)
        w = Entry()
        w.pack(side=side, expand=YES, fill=BOTH)
        w["textvariable"] = contents
        w.bind('<Key-Return>', command)
        return w

self = Tk()
app = VRFriend(master=self)
app.master.title("VR Friend")
app.master.minsize(200, 200)
app.mainloop()
self.destroy()
