#!/usr/bin/env python
 # -*- coding: latin -*-
import os
import time
import subprocess
import sys

FNAME = 0
CAMERA = 1
VIDEO = 2
PART = 3

def get_numbers(vname, fname):
    if vname in fname:
        read_complete = False
        i = fname.index(vname)+len(vname)
        str_number = ''
        while not read_complete:
            if not fname[i].isdigit():
                read_complete = True
            if not read_complete:
                str_number = str_number + fname[i]
                i += 1
        return int(str_number)

def categorize_from_fname(fname, project_root):
    camera = get_numbers('CAM', fname)
    video = get_numbers('VID', fname)
    part = get_numbers('PRT', fname)
    video_info = [project_root + '/' + fname.upper(), camera, video, part]
    return video_info


if len(sys.argv) > 1:
    project_root = sys.argv[1]
else:
    exit()
videos = []
for _file in os.listdir(project_root):
    if '.MP4' in _file:
        info = categorize_from_fname(_file, project_root)
        videos.append(info)
rig = []
new_cam = []
cam_latch = 1
for video in videos:
    if cam_latch != video[CAMERA]:
        rig.append(new_cam)
        new_cam = [video]
        cam_latch = video[CAMERA]
    else:
        new_cam.append(video)

print 'make ts\n'
# Make .ts maker Script
for video in videos:
    if '.MP4' in video[FNAME].upper():
        command = ('ffmpeg -i {!s}.MP4 -c copy -bsf:v h264_mp4toannexb -f mpegts {!s}.ts'.format(video[FNAME][:-4], video[FNAME][:-4]))
        # os.system(command)
        # time.sleep(10)
commands = []
i = 999999999
print '\nmake concat\n'
if not os.path.isdir(os.path.join(project_root, 'concat')):
    os.mkdir(os.path.join(project_root, 'concat'))
    os.system('touch {}/.hi'.format(os.path.join(project_root, 'concat')))
    time.sleep(10)
input_string = ''
for camera in rig:
    for video in camera:
        input_string = input_string + video[FNAME][:-4] + '.ts|'
        i = video[CAMERA]
    output_string = 'Camera_{}'.format(i)
    command = 'ffmpeg -i "concat:{!s}" -c copy -bsf:a aac_adtstoasc {}/{!s}.mp4'.format(input_string[:-1], os.path.join(project_root, 'concat'), output_string)
    # os.system(command)
    input_string = ''
    # time.sleep(10)
    print command + '\n'
